### ISSUE TITLE
Espresso `isDisplayed` incorrectly expects a view to be visible

### ISSUE THREAD

**Issue by ShivamPokhriyal** [android/android-test#1242]
### Description

I've a really simple constraintLayout with a textView in the middle of the screen and a linearLayout that covers the entire screen. 

```
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".MainActivity">

    <TextView
        android:id="@+id/text_view"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="Hello World!"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        app:layout_constraintTop_toTopOf="parent" />

    <LinearLayout
        android:id="@+id/cover_container"
        android:layout_width="0dp"
        android:layout_height="0dp"
        android:background="#fff"
        android:layout_gravity="center"
        android:gravity="center"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent">

        <Button
            android:id="@+id/error_button"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginTop="24dp"
            android:text="btn" />
    </LinearLayout>
</androidx.constraintlayout.widget.ConstraintLayout>
```

Now, when I run the app, you won't see the textView since it's hidden by the LinearLayout which covers the entire screen.
<img width="363" alt="Screenshot 2022-01-17 at 11 23 47 AM" src="https://user-images.githubusercontent.com/29516995/149718000-58a4d0a4-53d7-496e-9564-05ee858a103f.png">

And this is all expected. 

But when I write a test to assert the same behavior it fails. This is the test I wrote
```
@Test
    fun testTextView() {
        ActivityScenario.launch(MainActivity::class.java).onActivity {
            onView(withId(R.id.cover_container)).check(matches(isDisplayed()))
            onView(withId(R.id.text_view))
                .check(matches(not(isDisplayed())))
        }
    }
```
It waits for the activity to launch and then matches `text_view` to be `not displayed`. But the test fails with below error: 
```
'not (view has effective visibility <VISIBLE> and view.getGlobalVisibleRect() to return non-empty rectangle)' doesn't match the selected view.
Expected: not (view has effective visibility <VISIBLE> and view.getGlobalVisibleRect() to return non-empty rectangle)
     Got: was <com.google.android.material.textview.MaterialTextView{50b7d39c V.ED..... ......ID 154,187-166,228 #7f0801b2 app:id/text_view}>
View Details: MaterialTextView{id=2131231154, res-name=text_view, visibility=VISIBLE, width=12, height=41, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@2b850051, tag=null, root-is-layout-requested=false, has-input-connection=false, x=154.0, y=187.0, text=Hello World!, input-type=0, ime-target=false, has-links=false}

androidx.test.espresso.base.AssertionErrorHandler$AssertionFailedWithCauseError: 'not (view has effective visibility <VISIBLE> and view.getGlobalVisibleRect() to return non-empty rectangle)' doesn't match the selected view.
Expected: not (view has effective visibility <VISIBLE> and view.getGlobalVisibleRect() to return non-empty rectangle)
     Got: was <com.google.android.material.textview.MaterialTextView{50b7d39c V.ED..... ......ID 154,187-166,228 #7f0801b2 app:id/text_view}>
View Details: MaterialTextView{id=2131231154, res-name=text_view, visibility=VISIBLE, width=12, height=41, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@2b850051, tag=null, root-is-layout-requested=false, has-input-connection=false, x=154.0, y=187.0, text=Hello World!, input-type=0, ime-target=false, has-links=false}

	at java.base/java.lang.Thread.getStackTrace(Thread.java:1607)
	at androidx.test.espresso.base.AssertionErrorHandler.handleSafely(AssertionErrorHandler.java:3)
	at androidx.test.espresso.base.AssertionErrorHandler.handleSafely(AssertionErrorHandler.java:1)
	at androidx.test.espresso.base.DefaultFailureHandler$TypedFailureHandler.handle(DefaultFailureHandler.java:4)
	at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:5)
	at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:5)
	at androidx.test.espresso.ViewInteraction.check(ViewInteraction.java:12)
	at com.example.espressobugsample.MainActivityTest.testTextView$lambda-0(MainActivityTest.kt:21)
	at androidx.test.core.app.ActivityScenario.lambda$onActivity$2$ActivityScenario(ActivityScenario.java:661)
	at androidx.test.core.app.ActivityScenario$$Lambda$4.run(ActivityScenario.java:653)
	at androidx.test.core.app.ActivityScenario.onActivity(ActivityScenario.java:671)
	at com.example.espressobugsample.MainActivityTest.testTextView(MainActivityTest.kt:18)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:591)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:274)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:88)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: junit.framework.AssertionFailedError: 'not (view has effective visibility <VISIBLE> and view.getGlobalVisibleRect() to return non-empty rectangle)' doesn't match the selected view.
Expected: not (view has effective visibility <VISIBLE> and view.getGlobalVisibleRect() to return non-empty rectangle)
     Got: was <com.google.android.material.textview.MaterialTextView{50b7d39c V.ED..... ......ID 154,187-166,228 #7f0801b2 app:id/text_view}>
View Details: MaterialTextView{id=2131231154, res-name=text_view, visibility=VISIBLE, width=12, height=41, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@2b850051, tag=null, root-is-layout-requested=false, has-input-connection=false, x=154.0, y=187.0, text=Hello World!, input-type=0, ime-target=false, has-links=false}

	at androidx.test.espresso.matcher.ViewMatchers.assertThat(ViewMatchers.java:16)
	at androidx.test.espresso.assertion.ViewAssertions$MatchesViewAssertion.check(ViewAssertions.java:7)
	at androidx.test.espresso.ViewInteraction$SingleExecutionViewAssertion.check(ViewInteraction.java:2)
	at androidx.test.espresso.ViewInteraction$2.call(ViewInteraction.java:10)
	at androidx.test.espresso.ViewInteraction$2.call(ViewInteraction.java:1)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at android.os.Handler.$$robo$$android_os_Handler$handleCallback(Handler.java:938)
	at android.os.Handler.handleCallback(Handler.java)
	at android.os.Handler.$$robo$$android_os_Handler$dispatchMessage(Handler.java:99)
	at android.os.Handler.dispatchMessage(Handler.java)
	at org.robolectric.shadows.ShadowPausedLooper$IdlingRunnable.run(ShadowPausedLooper.java:332)
	at org.robolectric.shadows.ShadowPausedLooper.executeOnLooper(ShadowPausedLooper.java:366)
	at org.robolectric.shadows.ShadowPausedLooper.idle(ShadowPausedLooper.java:92)
	at org.robolectric.android.internal.LocalControlledLooper.drainMainThreadUntilIdle(LocalControlledLooper.java:17)
	at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:1)
	... 22 more

```

### Steps to Reproduce

Clone this minimal reproducible sample https://github.com/ShivamPokhriyal/EspressoBugSample and run `./gradlew :app:testDebugUnitTest --info`. 
Or add the above layout to any activity and test that the text_view is not displayed. 

### Expected Results

```
 onView(withId(R.id.text_view))
                .check(matches(not(isDisplayed())))
```
should succeed successfully. 

### Actual Results
```
 onView(withId(R.id.text_view))
                .check(matches(not(isDisplayed())))
```
fails with error: 
```
'not (view has effective visibility <VISIBLE> and view.getGlobalVisibleRect() to return non-empty rectangle)' doesn't match the selected view.
Expected: not (view has effective visibility <VISIBLE> and view.getGlobalVisibleRect() to return non-empty rectangle)
     Got: was <com.google.android.material.textview.MaterialTextView{50b7d39c V.ED..... ......ID 154,187-166,228 #7f0801b2 app:id/text_view}>
View Details: MaterialTextView{id=2131231154, res-name=text_view, visibility=VISIBLE, width=12, height=41, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@2b850051, tag=null, root-is-layout-requested=false, has-input-connection=false, x=154.0, y=187.0, text=Hello World!, input-type=0, ime-target=false, has-links=false}
```

### AndroidX Test and Android OS Versions

androidx.test: 1.4.0
OS: 31

### Link to a public git repo demonstrating the problem:

https://github.com/ShivamPokhriyal/EspressoBugSample

**Comment by ralf-at-android** [comment]
This is working as intended -- `isDisplayed` only validates the view visibility and presence in the view hierarchy.

To do a visual coverage test, consider using these `ViewMatcher` methods instead: [isCompletelyDisplayed](https://developer.android.com/reference/androidx/test/espresso/matcher/ViewMatchers#isCompletelyDisplayed()) and [isDisplayingAtLeast](https://developer.android.com/reference/androidx/test/espresso/matcher/ViewMatchers#isDisplayingAtLeast(int)) which allows to select a percentage. See javadoc for details.

**Comment by TWiStErRob** [comment]
I think even `isCompletelyDisplayed` will behave the same as the view is completely displayed, but also overlapped by another view.

Maybe have a look at https://developer.android.com/reference/androidx/test/espresso/assertion/LayoutAssertions
https://developer.android.com/reference/androidx/test/espresso/assertion/PositionAssertions

Although I see the pain, there should be an easy way to check for this.

**Comment by ShivamPokhriyal** [comment]
Confirming what @TWiStErRob said, `isCompletelyDisplayed` doesn't work for this case. 
And Thanks @TWiStErRob will try out your suggestions.

**Comment by ShivamPokhriyal** [comment]
@TWiStErRob I tried the LayoutAssertions but it didn't work. 
Just wanted to confirm whether this is the right way to use it: 

using `LayoutAssertions`
```
try {
                onView(withId(R.id.cover_container)).check(LayoutAssertions.noOverlaps(withId(R.id.text_view)))
                onView(withId(R.id.text_view)).check(LayoutAssertions.noOverlaps(withId(R.id.cover_container)))
            } catch (e: AssertionFailedError) {
                return@onActivity
            }
            fail("should've overlapped")
```

I also tried PositionAssertions, and although what I tested worked, but I'm not sure that the test is good enough to conclude which view is on top and visible and which is overlayed. 

This is what I wrote Using `PositionAssertions`: 
```
try {
                onView(withId(R.id.cover_container)).check(PositionAssertions.isCompletelyAbove(
                    withId(R.id.text_view)))
            } catch (e: AssertionFailedError) {
                try {
                    onView(withId(R.id.cover_container)).check(PositionAssertions.isCompletelyBelow(
                        withId(R.id.text_view)))
                } catch (e: AssertionFailedError) {
                    return@onActivity
                }
            }
            fail("should've overlapped")
```
This only concludes that the two views are overlapping with each other, but it doesn't make any assertions to which view is visible and which is hidden/overlayed. 
@TWiStErRob Can you please take a look whenever you get time. Really appreciate your help 🙂

**Comment by TWiStErRob** [comment]
A quick Google for the method yielded this: https://github.com/android/android-test/blob/master/testapps/ui_testapp/javatests/androidx/test/ui/app/LayoutTest.java#L58 which looks much more useful.

**Comment by ShivamPokhriyal** [comment]
Sorry for not being clear in the previous message, and thank you for providing the sample. I see that I can use `LayoutAssertions` as well to assert that there's an overlap: 
```
try {
                onView(isRoot()).check(noOverlaps())
            } catch (e: AssertionFailedError) {
                return@onActivity
            }
            fail("it fails to check overlapping")
```
and it works. It correctly asserts that there's some overlapping in the view. But it doesn't tell how much view is overlapped, like whether it's partially overlapped and still visible to the user, or is it completely overlapped and hidden to the user. 


**So basically what I want to assert is that a view is not only overlapped, but is completely hidden behind another view. In above example, I want to assert that the textView is not visible to the user because linearLayout is covering it completely.**

So, I need a way to ensure that the textview is completely overlapped by linearLayout. Since, `LayoutAssertions` doesn't provide whether overlapping is partial or full, I fall backed to `positionAssertions`

Right now, I'm able to assert these 2 things: 
- LinearLayout is not completely above textView. 
- LinearLayout is not completely below textView. 

But this doesn't guarantee that linearLayout is completely covering textView. 
Hope this made the question clear.

**Comment by ShivamPokhriyal** [comment]
Update: I'm able to assert that the `TextView's rect` is completely inside of `LinearLayout's rect`. **But this doesn't conclude that the TextView is hidden.** 

Consider these 2 layout hierarchies: 

layout 1: 
```
ConstraintLayout
  --TextView(at the center of screen)
  --LinearLayout(match_parent width and height)
```
In this layout, **TextView is hidden**(overlayed by linearLayout). 

layout 2: 
```
ConstraintLayout
  --LinearLayout(match_parent width and height)
  --TextView(at the center of screen)
```
In this layout, **TextView is visible,** because we changed it's order and  it's rendered after LinearLayout. 

In both these layouts, TextView's rect is completely inside LinearLayout's rect. Both for Layout 1 textView is hidden, and for layout 2, textView is visible. 

I also compared `elevation` and `translationZ` properties of TextView and LinearLayout but they're same for both views. So, I'm kinda stuck now. 

@TWiStErRob Can you point me in some direction for correctly asserting above behaviour?

**Comment by ralf-at-android** [comment]
@ShivamPokhriyal Consider combining `LayoutAssertions.noOverlaps()` with something like `PositionAssertions.isCompletelyAbove/Below()` (which do not seem to do what you want).
As none of the above fulfills your specific test logic, I'd also suggest writing your own custom matcher -- for example you can use the noOverlap() one and custom-write the "V1 within V2" matcher that you lack then combine them. You can use the implementation of the ones above as examples, they are easy to write.

**Comment by ShivamPokhriyal** [comment]
Thanks for the help @ralf-at-android. For posterity, I was able to find a solution to this. Idea is:
- First make sure view A's rect completely contains view B's rect.
- If true, make sure view A comes before view B in the layout xml.

Here's the code I used(with really terrible variable names): 
```

/**
 * This class checks that the current view being interacted is completely inside of the given view matcher.
 * It assumes that both the views are siblings. 
 * 
 * This method does 2 things to make the assertion:
 * - It asserts that the view being interacted is completely inside of the given view matcher.
 * - asserts that the view being interacted is placed closer to the root than the given view matcher.
 *   Implying view being interacted comes above the given view matcher in the layout xml.
 *
 * @param parentViewMatcher is the view which should completely cover the view that is being interacted.
 * 
 * Inspired by [PositionAssertions.relativePositionOf]
 */
private class IsCompletelyInsideViewAssertion(private val parentViewMatcher: Matcher<View>): ViewAssertion {
    override fun check(view: View?, noViewFoundException: NoMatchingViewException?) {
        if (noViewFoundException != null) {
            throw noViewFoundException
        }
        val childView = checkNotNull(view)
        val rootViewGroup = getImmediateViewGroup(childView)
        val parentView = findView(rootViewGroup)
        
        // check rect
        val childViewRect = getViewRect(childView)
        val parentViewRect = getViewRect(parentView)
        if (parentViewRect.contains(childViewRect)) {
            // check position in xml. 
            val root = checkNotNull(rootViewGroup)
            val parentViewDistance = root.indexOfChild(parentView)
            val childViewDistance = root.indexOfChild(childView)
            assertThat(parentViewDistance).isGreaterThan(childViewDistance)
        } else {
            throw ViewNotOverlappedException("parent view with rect ($parentViewRect) doesn't contain child view with rect ($childViewRect)")
        }
    }

    private fun getViewRect(view: View): Rect {
        val rect = Rect()
        view.getGlobalVisibleRect(rect)
        return rect
    }
    
    private fun getImmediateViewGroup(view: View): ViewGroup? {
        var currentParent = view.parent
        var topView: ViewGroup? = null
        while (currentParent != null) {
            if (currentParent is ViewGroup) {
                topView = currentParent
                return topView
            }
            currentParent = currentParent.parent
        }
        return topView
    }
    
    private fun findView(rootViewGroup: View?): View {
        val root = checkNotNull(rootViewGroup)
        val viewPredicate = Predicate<View> { input -> parentViewMatcher.matches(input) }
        val matchedViewIterator: Iterator<View> = 
            Iterables
                .filter(TreeIterables.breadthFirstViewTraversal(root), viewPredicate)
                .iterator()
        
        var matchedView: View? = null
        while (matchedViewIterator.hasNext()) {
            matchedView = if (matchedView != null) {
                // we found 2 views, throw exception
                throw AmbiguousViewMatcherException.Builder()
                    .withRootView(root)
                    .withViewMatcher(parentViewMatcher)
                    .withView1(matchedView)
                    .withView2(matchedViewIterator.next())
                    .withOtherAmbiguousViews(
                        *Iterators.toArray(
                            matchedViewIterator,
                            View::class.java
                        )
                    )
                    .build()
            } else {
                matchedViewIterator.next()
            }
        }
        if (matchedView == null) {
            throw NoMatchingViewException.Builder()
                .withViewMatcher(parentViewMatcher)
                .withRootView(root)
                .build()
        }
        return matchedView
    }
}

private class ViewNotOverlappedException(msg: String): RuntimeException(msg)

fun isCompletelyInside(parent: Matcher<View>): ViewAssertion = IsCompletelyInsideViewAssertion(parent)
```

**Comment by CoolMind** [comment]
In my case it was not expected screen. Reinstalling of an application helped. Then needed buttons appeared.
