### ISSUE TITLE
Running a test with ActivityScenario while test coverage is enabled throws a NoClassDefFoundError

### ISSUE THREAD

**Issue by aljohnston112** [android/android-test#1377]
### Steps to Reproduce

Follow the steps here to get Jacoco coverage for tests
 
https://about.codecov.io/blog/code-coverage-for-android-development-using-kotlin-jacoco-github-actions-and-codecov/

Try to run this test

```
@RunWith(AndroidJUnit4::class)
class StringAdapterTest {

    @Test
    fun testStringAdapter() {
        ActivityScenario.launch(
            TestActivity::class.java
        ).onActivity { activity ->

            }

        }

}
```

### Expected Results

No exceptions.

### Actual Results

    java.lang.NoClassDefFoundError: Failed resolution of: Lorg/jacoco/agent/rt/internal_3570298/Offline;
        at androidx.test.core.app.InstrumentationActivityInvoker$BootstrapActivity.$jacocoInit(Unknown Source:13)
        at androidx.test.core.app.InstrumentationActivityInvoker$BootstrapActivity.<clinit>(Unknown Source:0)
        at java.lang.Class.newInstance(Native Method)
        at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1253)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3725)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4022)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2336)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8653)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "org.jacoco.agent.rt.internal_3570298.Offline" on path: DexPathList[[zip file "/data/app/~~h8MxzSzcV5J1qu2yJeU5Dg==/com.example.inventory_manager.test-OTl1KcxOXWG6CFw7svj1Pg==/base.apk"],nativeLibraryDirectories=[/data/app/~~h8MxzSzcV5J1qu2yJeU5Dg==/com.example.inventory_manager.test-OTl1KcxOXWG6CFw7svj1Pg==/lib/arm64, /system/lib64, /system/system_ext/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at androidx.test.core.app.InstrumentationActivityInvoker$BootstrapActivity.$jacocoInit(Unknown Source:13) 
        at androidx.test.core.app.InstrumentationActivityInvoker$BootstrapActivity.<clinit>(Unknown Source:0) 
        at java.lang.Class.newInstance(Native Method) 
        at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95) 
        at android.app.Instrumentation.newActivity(Instrumentation.java:1253) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3725) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4022) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2336) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:246) 
        at android.app.ActivityThread.main(ActivityThread.java:8653) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130) 

### AndroidX Test and Android OS Versions

AndroidX Test version 1.4.0 and Android OS Version 11

**Comment by aljohnston112** [comment]
Ah, so if I remove Jacoco related stuff, I still get the same error

**Comment by aljohnston112** [comment]
I forced Jacoco version 0.8.7 and see all Jacoco related dependencies are 0.8.7 in buildEnvironment

**Comment by mikehardy** [comment]
We are currently on 0.8.8 with no issue
We were on 0.8.7 with no issue
Prior to that, no issue, we haven't had issues with this, git blame link:
https://github.com/ankidroid/Anki-Android/blame/main/AnkiDroid/jacoco.gradle#L6

**Comment by mikehardy** [comment]
Perhaps you should specify the JDK in use? We use JDK11 for build + test execution.

**Comment by aljohnston112** [comment]
compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    
Whatever version that is.

**Comment by aljohnston112** [comment]
I am pretty sure it is related to ActivityScenario because I use AndroidJUnit4 on other tests and they work. Same with org.junit.Test and  org.junit.runner.RunWith

**Comment by aljohnston112** [comment]
Here is a minimal reproducible example
https://github.com/aljohnston112/TestJacocoBug/tree/main

**Comment by aljohnston112** [comment]
Looks like a bug with ActivityScenario or AppCompatActivity. I think there is some kind of conflict between  'androidx.test:core-ktx:1.4.0' and 'com.google.android.material:material:1.6.1'.

**Comment by aljohnston112** [comment]
Using an android.app.Activity does not work either

**Comment by TWiStErRob** [comment]
Just a blind stab: can it be that you need to put `org.jacoco` into the first dex?

**Comment by aljohnston112** [comment]
-keep class org.jacoco.** { *; }
and
debug {
            testCoverageEnabled true
            multiDexKeepProguard file('multidex-config.pro')
        }
 
Didn't help

**Comment by aljohnston112** [comment]
Wow, so I needed ```debugImplementation 'androidx.test:core-ktx:1.4.0'```. ```androidTestImplementation 'androidx.test:core-ktx:1.4.0'``` was not enough.

**Comment by aljohnston112** [comment]
Definitely something to add here 
https://developer.android.com/training/testing/instrumented-tests/androidx-test-libraries/test-setup
unless it actually is a bug.

**Comment by aljohnston112** [comment]
On another note, trying to debug with the test in the minimal reproducible example causes a NumberFormatException as the program is trying to parse "config_mainBuiltInDisplayCutout" as a number

**Comment by aljohnston112** [comment]
Hmmm, a rebuild fixed that

**Comment by dmytroKarataiev** [comment]
> Wow, so I needed debugImplementation 'androidx.test:core-ktx:1.4.0'. androidTestImplementation 'androidx.test:core-ktx:1.4.0' was not enough.

What a catch. Definitely solves the problem.

**Comment by EdinSe** [comment]
> > Wow, so I needed debugImplementation 'androidx.test:core-ktx:1.4.0'. androidTestImplementation 'androidx.test:core-ktx:1.4.0' was not enough.
> 
> What a catch. Definitely solves the problem.

I can confirm that this solved the issue for me too. I didn't even have this dependency before. When I did upgrade to AGP 7.2.2 and Gradle 7.4.2 instrumentation tests started failing. Also, removing `testCoverageEnabled true` resolved tests crashing but I need that because of the Jacoco setup. The error I had was this one:

```
java.lang.AssertionError: Activity never becomes requested state "[CREATED, STARTED, RESUMED, DESTROYED]" (last lifecycle transition = "PRE_ON_CREATE")
        at androidx.test.core.app.ActivityScenario.waitForActivityToBecomeAnyOf(ActivityScenario.java:338)
```
