### ISSUE TITLE
Unable to find explicit activity class BootstrapActivity

### ISSUE THREAD

**Issue by sophiataskova** [android/android-test#196]
### Description

Making my first attempts at using ActivityScenario, and I immediately stumbled upon this exception

```
android.content.ActivityNotFoundException: Unable to find explicit activity class {com.me.debug.test/androidx.test.core.app.InstrumentationActivityInvoker$BootstrapActivity}; have you declared this activity in your AndroidManifest.xml?
at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2005)
at android.app.Instrumentation.execStartActivity(Instrumentation.java:1673)
at androidx.test.runner.MonitoringInstrumentation.execStartActivity(MonitoringInstrumentation.java:508)
at android.app.ContextImpl.startActivity(ContextImpl.java:917)
at android.app.ContextImpl.startActivity(ContextImpl.java:888)
at androidx.test.core.app.InstrumentationActivityInvoker.startActivity(InstrumentationActivityInvoker.java:352)
at androidx.test.core.app.ActivityScenario.launch(ActivityScenario.java:207)
at androidx.test.core.app.ActivityScenario.launch(ActivityScenario.java:184)
at androidx.test.ext.junit.rules.ActivityScenarioRule.lambda$new$0$ActivityScenarioRule(ActivityScenarioRule.java:68)
at androidx.test.ext.junit.rules.ActivityScenarioRule$$Lambda$0.get(Unknown Source:2)
at androidx.test.ext.junit.rules.ActivityScenarioRule.before(ActivityScenarioRule.java:82)
at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:46)
at org.junit.rules.RunRules.evaluate(RunRules.java:20)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at androidx.test.runner.AndroidJUnit4.run(AndroidJUnit4.java:104)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:388)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2145) 
```

### Steps to Reproduce

Here's my code:

```
import androidx.test.core.app.ActivityScenario
import androidx.test.ext.junit.rules.ActivityScenarioRule
import androidx.test.runner.AndroidJUnit4
import com.me.MainActivity
import org.junit.Before
import org.junit.Rule
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(AndroidJUnit4::class)
class SampleTest {

  private var scenario: ActivityScenario<MainActivity>? = null

  @get:Rule
  val mainActivityScenarioRule = ActivityScenarioRule<MainActivity>(MainActivity::class.java)

  @Before
  fun init() {
    scenario = mainActivityScenarioRule.scenario
  }

  @Test
  fun basicUseCase() {
  }
}
```

### Expected Results

`scenario` gets created and I'm able to drive MainActivity's lifecycle with it

### Actual Results

android.content.ActivityNotFoundException

### AndroidX Test and Android OS Versions

```
    androidTestImplementation "androidx.test:runner:$androidx_test_runner_version"
    androidTestImplementation "androidx.test.espresso:espresso-core:$androidx_test_espresso_version"
    androidTestImplementation "androidx.test.espresso:espresso-contrib:$androidx_test_espresso_version"
    androidTestImplementation "androidx.test.espresso:espresso-intents:$androidx_test_espresso_version"
    androidTestImplementation "androidx.test.uiautomator:uiautomator:$androidx_test_uiautomator_version"
    androidTestImplementation "androidx.test.ext:junit:$androidx_test_ext_version"
    androidTestImplementation "androidx.test.ext:junit-ktx:$androidx_test_ext_version"
    androidTestImplementation "com.google.truth:truth:$google_truth_version"

```

where 

```
    androidx_test_runner_version = '1.1.1'
    androidx_test_espresso_version = '3.1.1'
    androidx_test_uiautomator_version = '2.2.0'
    androidx_test_ext_version = '1.1.0'
```

### Link to a public git repo demonstrating the problem:
Let me know if I should make one, I wonder if I'm just missing something obvious and this isn't a bug.

**Comment by sophiataskova** [comment]
Issue was entirely on my end!

**Comment by michaelbukachi** [comment]
@sophiataskova  how did you solve your issue? Facing the same issue.

**Comment by copolii** [comment]
@sophiataskova it would be really n ice if you had left a little more detail as to what you did wrong and what you did to fix it on your end.

**Comment by subprogram** [comment]
Uninstalling of the test package is helped in my case.

**Comment by leonardosibela** [comment]
@sophiataskova  how did you solve your issue? Facing the same issue.

**Comment by MattWilliams89** [comment]
Can anyone please share how they resolved this?

**Comment by MattWilliams89** [comment]
Adding 		

```		
<activity
   android:name="androidx.test.core.app.InstrumentationActivityInvoker$BootstrapActivity"
   android:label="InstrumentationActivityInvoker$BootstrapActivity" />
```

to the AndroidManifest of the androidTest sourceSet seems to work, but this feels like a workaround.

**Comment by lassana** [comment]
I've started seeing this but only on Android 4.4. `InstrumentationActivityInvoker$BootstrapActivity` class is obviously in the DEX file. What can cause this?

```
java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.example.Example.test/androidx.test.core.app.InstrumentationActivityInvoker$BootstrapActivity}: java.lang.ClassNotFoundException: Didn't find class "androidx.test.core.app.InstrumentationActivityInvoker$BootstrapActivity" on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/data/app/com.example.Example.test-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.example.Example.test-2, /vendor/lib, /system/lib]]
```

**Comment by Keremturker** [comment]
> Adding
> 
> ```
> <activity
>    android:name="androidx.test.core.app.InstrumentationActivityInvoker$BootstrapActivity"
>    android:label="InstrumentationActivityInvoker$BootstrapActivity" />
> ```
> 
> to the AndroidManifest of the androidTest sourceSet seems to work, but this feels like a workaround.

it works for me. Thank you :)

**Comment by elevenfive** [comment]
For Android 13 devices, this is fixed in `androidx.test:core:1.5.0-alpha02`, see: https://github.com/android/android-test/issues/1412

**Comment by VuNgN** [comment]
> For Android 13 devices, this is fixed in `androidx.test:core:1.5.0-alpha02`, see: #1412

It works for me. Thank you 😄

**Comment by krischik** [comment]
> Issue was entirely on my end!

That happens sometimes. But how did you solve it? This is the top search result for the problem. Many people are interested to know how you solved the problem.

**Comment by DonMykl** [comment]
> For Android 13 devices, this is fixed in `androidx.test:core:1.5.0-alpha02`, see: #1412

Thanks for this, saving for later
