### ISSUE TITLE
android.view.InflateException: Binary XML file line #9: Binary XML file line #9: Error inflating class com.google.android.material.textfield.TextInputLayout

### ISSUE THREAD

**Issue by thrlr123** [android/android-test#206]
### On migrating to Android with robolectric 4.1 and with FragmentScenario for testing fragments in isolation, I am seeing an issue when I try to run this:
`FragmentScenario.launchInContainer(Fragment.class);`

Log:

```java
android.view.InflateException: Binary XML file line #9: Binary XML file line #9: Error inflating class **com.google.android.material.textfield.TextInputLayout**

Caused by: android.view.InflateException: Binary XML file line #9: Error inflating class **com.google.android.material.textfield.TextInputLayout**
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at android.view.LayoutInflater.$$robo$$android_view_LayoutInflater$createView(LayoutInflater.java:647)
	at android.view.LayoutInflater.createView(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$android_view_LayoutInflater$createViewFromTag(LayoutInflater.java:790)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$android_view_LayoutInflater$createViewFromTag(LayoutInflater.java:730)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$android_view_LayoutInflater$rInflate(LayoutInflater.java:863)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$android_view_LayoutInflater$rInflateChildren(LayoutInflater.java:824)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$android_view_LayoutInflater$inflate(LayoutInflater.java:515)
	at android.view.LayoutInflater.inflate(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$android_view_LayoutInflater$inflate(LayoutInflater.java:423)
	at android.view.LayoutInflater.inflate(LayoutInflater.java)
	at com.arubanetworks.appviewer.activities.Fragment.onCreateView(Fragment.java:224)
	at androidx.fragment.app.Fragment.$$robo$$androidx_fragment_app_Fragment$performCreateView(Fragment.java:2485)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java)
	at androidx.fragment.app.FragmentManagerImpl.$$robo$$androidx_fragment_app_FragmentManagerImpl$moveToState(FragmentManagerImpl.java:888)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java)
	at androidx.fragment.app.FragmentManagerImpl.$$robo$$androidx_fragment_app_FragmentManagerImpl$moveFragmentToExpectedState(FragmentManagerImpl.java:1234)
	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java)
	at androidx.fragment.app.FragmentManagerImpl.$$robo$$androidx_fragment_app_FragmentManagerImpl$moveToState(FragmentManagerImpl.java:1300)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java)
	at androidx.fragment.app.BackStackRecord.$$robo$$androidx_fragment_app_BackStackRecord$executeOps(BackStackRecord.java:688)
	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java)
	at androidx.fragment.app.FragmentManagerImpl.$$robo$$androidx_fragment_app_FragmentManagerImpl$executeOps(FragmentManagerImpl.java:2062)
	at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java)
	at androidx.fragment.app.FragmentManagerImpl.$$robo$$androidx_fragment_app_FragmentManagerImpl$executeOpsTogether(FragmentManagerImpl.java:1852)
	at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java)
	at androidx.fragment.app.FragmentManagerImpl.$$robo$$androidx_fragment_app_FragmentManagerImpl$removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1807)
	at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java)
	at androidx.fragment.app.FragmentManagerImpl.$$robo$$androidx_fragment_app_FragmentManagerImpl$execSingleAction(FragmentManagerImpl.java:1684)
	at androidx.fragment.app.FragmentManagerImpl.execSingleAction(FragmentManagerImpl.java)
	at androidx.fragment.app.BackStackRecord.$$robo$$androidx_fragment_app_BackStackRecord$commitNow(BackStackRecord.java:531)
	at androidx.fragment.app.BackStackRecord.commitNow(BackStackRecord.java)
	at androidx.fragment.app.testing.FragmentScenario$1.$$robo$$androidx_fragment_app_testing_FragmentScenario_1$perform(FragmentScenario.java:307)
	at androidx.fragment.app.testing.FragmentScenario$1.perform(FragmentScenario.java)
	at androidx.fragment.app.testing.FragmentScenario$1.perform(FragmentScenario.java:285)
	at androidx.test.core.app.ActivityScenario.lambda$onActivity$1$ActivityScenario(ActivityScenario.java:527)
	at androidx.test.core.app.ActivityScenario$$Lambda$0.run(Unknown Source)
	at org.robolectric.android.fakes.RoboMonitoringInstrumentation.runOnMainSync(RoboMonitoringInstrumentation.java:61)
	at androidx.test.core.app.ActivityScenario.onActivity(ActivityScenario.java:520)
	at androidx.fragment.app.testing.FragmentScenario.$$robo$$androidx_fragment_app_testing_FragmentScenario$internalLaunch(FragmentScenario.java:284)
	at androidx.fragment.app.testing.FragmentScenario.internalLaunch(FragmentScenario.java)
	at androidx.fragment.app.testing.FragmentScenario.$$robo$$androidx_fragment_app_testing_FragmentScenario$launchInContainer(FragmentScenario.java:265)
	at androidx.fragment.app.testing.FragmentScenario.launchInContainer(FragmentScenario.java)
	at androidx.fragment.app.testing.FragmentScenario.$$robo$$androidx_fragment_app_testing_FragmentScenario$launchInContainer(FragmentScenario.java:244)
	at androidx.fragment.app.testing.FragmentScenario.launchInContainer(FragmentScenario.java)
	at androidx.fragment.app.testing.FragmentScenario.$$robo$$androidx_fragment_app_testing_FragmentScenario$launchInContainer(FragmentScenario.java:226)
	at androidx.fragment.app.testing.FragmentScenario.launchInContainer(FragmentScenario.java)
	at androidx.fragment.app.testing.FragmentScenario.$$robo$$androidx_fragment_app_testing_FragmentScenario$launchInContainer(FragmentScenario.java:210)
	at androidx.fragment.app.testing.FragmentScenario.launchInContainer(FragmentScenario.java)
	at com.arubanetworks.appviewer.AcFragmentTest.testEventFragment(AcFragmentTest.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:601)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:260)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:130)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:42)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:84)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at androidx.test.ext.junit.runners.AndroidJUnit4.run(AndroidJUnit4.java:104)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:131)
**Caused by: java.lang.IllegalArgumentException: The style on this component requires your app theme to be Theme.AppCompat (or a descendant).**
	at com.google.android.material.internal.ThemeEnforcement.checkTheme(ThemeEnforcement.java:221)
	at com.google.android.material.internal.ThemeEnforcement.checkAppCompatTheme(ThemeEnforcement.java:196)
	at com.google.android.material.internal.ThemeEnforcement.checkCompatibleTheme(ThemeEnforcement.java:131)
	at com.google.android.material.internal.ThemeEnforcement.obtainTintedStyledAttributes(ThemeEnforcement.java:110)
	at com.google.android.material.textfield.TextInputLayout.<init>(TextInputLayout.java:266)
	at com.google.android.material.textfield.TextInputLayout.<init>(TextInputLayout.java:247)
	... 87 more
```

XML:

```
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:layout_marginTop="?android:attr/actionBarSize"
    android:background="@color/white">

 **<com.google.android.material.textfield.TextInputLayout**
        android:id="@+id/facc_inputlayout_email"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_gravity="center_horizontal"
        android:layout_marginTop="8dp"
        android:layout_marginEnd="16dp"
        android:layout_marginStart="16dp"
        android:hint="@string/account_username_hint"
        android:labelFor="@+id/facc_email"
        app:hintTextAppearance="@style/ABC.FloatingLabelTextAppearance">
        <com.google.android.material.textfield.TextInputEditText
            android:id="@+id/facc_email"
            android:layout_width="match_parent"
            android:layout_height="48dp"
            app:backgroundTint="@color/appviewer_text_grey_lighter"
            android:ems="10"
            android:inputType="textEmailAddress"
            android:textAppearance="@style/ABC.Widget.TextView.OpenSansRegular"
            android:textColor="@color/appviewer_text_grey_dark"
            android:textColorHint="@color/appviewer_text_grey_light"
            android:textSize="16sp" />
    **</com.google.android.material.textfield.TextInputLayout>**
```

**Comment by thrlr123** [comment]
This article suggests that if you are not using the material theme then add the style (Scroll to section **5. Add a Material component to your app** in the link below )
https://material.io/components/android/docs/getting-started/

So...I changed it to:
<com.google.android.material.textfield.TextInputLayout
**style="@style/Widget.MaterialComponents.TextInputLayout.FilledBox"**
android:id="@+id/facc_inputlayout_email"
android:layout_width="match_parent"
android:layout_height="wrap_content"
android:layout_gravity="center_horizontal"
android:layout_marginTop="8dp"
android:layout_marginEnd="16dp"
android:layout_marginStart="16dp"
android:hint="@string/account_username_hint"
android:labelFor="@+id/facc_email"
app:hintTextAppearance="@style/ABC.FloatingLabelTextAppearance">

but still no luck.

**Comment by NitroG42** [comment]
It happens because the activity that starts fragment doesn't use a Material or AppCompat theme.
It's not your activity, it comes from the testing library.
You can instruct which theme to use by calling :
launchInContainer(Class<F> fragmentClass, Bundle fragmentArgs, int themeResId, FragmentFactory factory)

**Comment by thrlr123** [comment]
Yeah! This has been resolved acc. to this suggestion:
https://github.com/robolectric/robolectric/issues/4610#issuecomment-462456057
