### ISSUE TITLE
[Espresso-Flutter] Failed assertion: line 186 pos 14: 'WidgetsBinding.instance.isRootWidgetAttached || !command.requiresRootWidgetAttached'

### ISSUE THREAD

**Issue by adazh** [android/android-test#384]
06-10 23:44:02.438 16655 16655 D JsonRpcClient: JSON-RPC Request sent to uri ws://127.0.0.1:59904/y-HoF72rrXc=/ws: {"id":"message-2","method":"ext.flutter.driver","params":{"isolateId":"isolates/root","command":"waitUntilNoTransientCallbacks","timeout":10000},"jsonrpc":"2.0"}.
06-10 23:44:02.470 16655 16691 D JsonRpcClient: JSON-RPC response received: {"jsonrpc":"2.0","result":{"isError":true,"response":"Uncaught extension error while executing waitUntilNoTransientCallbacks: 'package:flutter_driver/src/extension/extension.dart': Failed assertion: line 186 pos 14: 'WidgetsBinding.instance.isRootWidgetAttached || !command.requiresRootWidgetAttached': No root widget is attached; have you remembered to call runApp()?\n#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:40:39)\n#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)\n#2      FlutterDriverExtension.call (package:flutter_driver/src/extension/extension.dart:186:14)\n<asynchronous suspension>\n#3      BindingBase.registerServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart:512:32)\n<asynchronous suspension>\n#4      _runExtension (dart:developer-patch/developer.dart:84:23)\n","type":"_extensionType","method":"ext.flutter.driver"},"id":"message-2"}.

**Comment by adazh** [comment]
cc @goderbauer

**Comment by adazh** [comment]
We'll need to wait for the first frame to be rendered before sending any request. Asking to see if there's an API that we could use in native land.

**Comment by adazh** [comment]
Matt is going to help create an API on FlutterView for querying the first frame rendering state. See https://github.com/flutter/flutter/issues/34275.
