### ISSUE TITLE
android_support_test_services.speak_easy returns null!

### ISSUE THREAD

**Issue by tir38** [android/android-test#397]
### Description

Getting this crash running instrumentation tests

```
2019-06-24 16:39:13.106 1906-1923/? I/ActivityManager: Start proc 8485:androidx.test.services/u0a233 for content provider androidx.test.services/.speakeasy.server.SpeakEasyContentProvider
2019-06-24 16:39:13.113 8485-8485/? W/x.test.service: Unexpected CPU variant for X86 using defaults: x86
2019-06-24 16:39:13.144 1906-3001/? D/ActivityManager: Raise procstate to external provider: ProcessRecord{6462c6c 8485:androidx.test.services/u0a233}
2019-06-24 16:39:13.162 8485-8485/androidx.test.services I/x.test.service: The ClassLoaderContext is a special shared library.
2019-06-24 16:39:13.194 1906-3000/? D/ActivityManager: Raise procstate to external provider: ProcessRecord{6462c6c 8485:androidx.test.services/u0a233}
2019-06-24 16:39:13.195 8475-8475/? I/ToolConnection: Getting the provider field
2019-06-24 16:39:13.195 8475-8475/? I/ToolConnection: Finding the call method
2019-06-24 16:39:13.195 8475-8475/? I/ToolConnection: Invoking modern call method
2019-06-24 16:39:13.198 1906-3007/? D/ActivityManager: Raise procstate to external provider: ProcessRecord{6462c6c 8485:androidx.test.services/u0a233}
2019-06-24 16:39:13.203 8475-8475/? I/ToolConnection: Intent sent!
2019-06-24 16:39:13.203 8475-8475/? I/ToolConnection: Releasing content provider
2019-06-24 16:39:13.203 8475-8475/? I/ToolConnection: Invoking getService
2019-06-24 16:39:13.207 8475-8475/? I/ToolConnection: Released content provider
2019-06-24 16:39:13.208 8475-8475/? I/ToolConnection: looking up IActivityManager
2019-06-24 16:39:13.208 8475-8475/? I/ToolConnection: looking up getContentProviderExternal
2019-06-24 16:39:13.208 8475-8475/? I/ToolConnection: looking up removeContentProviderExternal
2019-06-24 16:39:13.208 8475-8475/? I/ToolConnection: Getting a content provider holder for: android_support_test_services.speak_easy
2019-06-24 16:39:13.208 8475-8475/? I/ToolConnection: Invoking getService
2019-06-24 16:39:13.211 8475-8475/? I/ToolConnection: Releasing content provider
2019-06-24 16:39:13.211 8475-8475/? I/ToolConnection: Invoking getService
2019-06-24 16:39:13.213 8475-8475/? I/ToolConnection: Released content provider
2019-06-24 16:39:13.213 8475-8475/? D/AndroidRuntime: Shutting down VM
2019-06-24 16:39:13.214 8475-8475/? E/AndroidRuntime: FATAL EXCEPTION: main
    PID: 8475
    java.lang.IllegalStateException: Call to getContentProviderExternal for: android_support_test_services.speak_easy returns null!
        at androidx.test.services.speakeasy.client.ToolConnection$ToolConnectionPostIcs.doCall(ToolConnection.java:155)
        at androidx.test.services.speakeasy.client.ToolConnection.publish(ToolConnection.java:93)
        at androidx.test.services.speakeasy.client.ToolConnection.publish(ToolConnection.java:83)
        at androidx.test.services.shellexecutor.BlockingPublish.getResult(BlockingPublish.java:79)
        at androidx.test.services.shellexecutor.ShellCommandExecutorServer.start(ShellCommandExecutorServer.java:80)
        at androidx.test.services.shellexecutor.ShellMain.main(ShellMain.java:45)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:340)
2019-06-24 16:39:13.214 8475-8475/? E/AndroidRuntime: Error reporting crash
    java.lang.RuntimeException: Bad file descriptor
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:1127)
        at android.app.IActivityManager$Stub$Proxy.handleApplicationCrash(IActivityManager.java:3711)
        at com.android.internal.os.RuntimeInit$KillApplicationHandler.uncaughtException(RuntimeInit.java:143)
        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
        at java.lang.Thread.dispatchUncaughtException(Thread.java:1955)
```

### Steps to Reproduce

We have some instrumentation tests. Running these tests sometimes generates the above error. 

In command line we then see

```
com.android.builder.testing.ConnectedDevice > No tests found.[Nexus_5X_API_25(AVD) - 7.1.1] FAILED
No tests found. This usually means that your test classes are not in the form that your test runner expects (e.g. don't inherit from TestCase or lack @Test annotations).
```

I have confirmed that we use `@Test` on each test.

This is happening for random developers, while tests pass fine for others (same tests, same branch, different machine and tests pass just fine.) Switching to a previously working branch does not solve the problem. clearing gradle cache does not solve the problem. Switching emulator / test device does not solve the problem, invalidate cache/restart does not solve the problem.

The tests then fail 

### Expected Results

tests should run

### Actual Results

above error

### AndroidX Test and Android OS Versions

```
AGP `3.5.0-beta04` 
androidXTestRunnerVersion = '1.2.0' 
androidXTestRulesVersion = '1.2.0'
androidXTestOrchestratorVersion = '1.2.0'

testing on API 28 and 25
```

### Link to a public git repo demonstrating the problem:

none

**Comment by tir38** [comment]
I noticed that even though i had everything pointing to 1.2.0 that for some reason the resultant orchestrator apk was still very old (1.1.0-alpha3). Clearing gradle cache didn't solve the problem.

```
4:08:16 D/orchestrator-1.1.0-alpha3.apk: Uploading orchestrator-1.1.0-alpha3.apk onto device '9889db34454f5a4f56'
04:08:16 D/ddms: Reading file permision of /Users/user/.gradle/caches/modules-2/files-2.1/androidx.test/orchestrator/1.1.0-alpha3/2131e94d82bcc0eb6197f1fce8753cae37b01619/orchestrator-1.1.0-alpha3.apk as: rw-r--r--
04:08:16 V/ddms: execute: running pm install -r -t "/data/local/tmp/orchestrator-1.1.0-alpha3.apk"
04:08:30 V/ddms: execute 'pm install -r -t "/data/local/tmp/orchestrator-1.1.0-alpha3.apk"' on '9889db34454f5a4f56' : EOF hit. Read: -1
04:08:30 V/ddms: execute: running rm "/data/local/tmp/orchestrator-1.1.0-alpha3.apk"
04:08:30 V/ddms: execute 'rm "/data/local/tmp/orchestrator-1.1.0-alpha3.apk"' on '9889db34454f5a4f56' : EOF hit. Read: -1
```

**Comment by tir38** [comment]
Derp

`$ ./gradlew app:dependencies > output.txt`

output.txt contained:

```
androidTestUtil - Additional APKs used during instrumentation testing.
\--- com.android.support.test:orchestrator:1.2.0 -> androidx.test:orchestrator:1.1.0-alpha3
     \--- androidx.test.services:test-services:1.1.0-alpha3
```
 
 Then I realized that I had upgraded all the *other* android test dependencies to AndroidX, but our orchestrator version had accidentally still pointed to android.support:

```
const val AndroidX_Junit = "androidx.test.ext:junit:1.1.1"
const val AndroidX_TestRunner = "androidx.test:runner:1.2.0"
const val AndroidX_TestRules = "androidx.test:rules:1.2.0"
const val AndroidX_Test_Orchestrator = "com.android.support.test:orchestrator:1.2.0"
```

After updating to AndroidX everything worked fine 🤦‍♂ 

```
const val AndroidX_Junit = "androidx.test.ext:junit:1.1.1"
const val AndroidX_TestRunner = "androidx.test:runner:1.2.0"
const val AndroidX_TestRules = "androidx.test:rules:1.2.0"
const val AndroidX_Test_Orchestrator = "androidx.test:orchestrator:1.2.0"
```

Side note: I'm not even sure how that compiled. There is no version 1.2.0 of the support lib. All I can guess is that maven central knows that that artifact was super seeded by androidx.test and just grabbed the oldest version

https://mvnrepository.com/artifact/com.android.support.test/orchestrator

**Comment by gildor** [comment]
I have the same issue with Orchestrator 1.3.0-beta01, all dependencies including runner and orchestartor use 1.3.0-beta01
