### ISSUE TITLE
TestActivity doesn't start in app module

### ISSUE THREAD

**Issue by nihk** [android/android-test#665]
### Description
I have an androidTest file that launches an Activity that lives in the same androidTest directory. This test passes in library modules but not app modules.

### Steps to Reproduce
Add a test to an application module that has the following code and run it

```
@RunWith(AndroidJUnit4::class)
class TestActivityTest {

    @Test
    fun runMe() {
        launchActivity<TestActivity>()
        assertTrue(true)
    }
}

class TestActivity : Activity()
```

You'll also have to have an AndroidManifest.xml in the androidTest directory where that Activity is described, which'll look something like:

```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="ca.nick.testactivity">

    <application>
        <activity android:name=".TestActivity" />
    </application>

</manifest>
```

### Expected Results
Test passes when run in either an application module or library module.

### Actual Results
Test fails after 45 seconds when run in an application module with the following stacktrace:

```
java.lang.AssertionError: Activity never becomes requested state "[STARTED, DESTROYED, CREATED, RESUMED]" (last lifecycle transition = "PRE_ON_CREATE")
at androidx.test.core.app.ActivityScenario.waitForActivityToBecomeAnyOf(ActivityScenario.java:338)
at androidx.test.core.app.ActivityScenario.launchInternal(ActivityScenario.java:272)
at androidx.test.core.app.ActivityScenario.launch(ActivityScenario.java:207)
at ca.nick.testactivity.TestActivityTest.runMe(TestActivityTest.kt:25)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:395)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2196)
```

It passes, however, when run in a library module. That is, if in the app module's `build.gradle` you change `apply plugin: 'com.android.application'` to `apply plugin: 'com.android.library'` and remove the `android.defaultConfig.applicationId`, the test will run and pass.

### AndroidX Test and Android OS Versions
```
    androidTestImplementation 'androidx.annotation:annotation:1.1.0'
    androidTestImplementation 'androidx.test.ext:junit:1.1.1'
    def test_version = "1.3.0-rc01"
    androidTestImplementation "androidx.test:rules:$test_version"
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
    androidTestImplementation "androidx.test:core-ktx:$test_version"
    androidTestImplementation "androidx.test:runner:$test_version"
```

Run on a Pixel 3XL running Android 10.

### Link to a public git repo demonstrating the problem:
https://github.com/nihk/TestActivityBugReport

**Comment by nihk** [comment]
Looks like this is more an issue with AndroidManifest.xml merging than android-test. My workaround is to either put the TestActivity.kt in a src/debug folder or in the production code folder, or move the code under test to a library module.

**Comment by myungjunChae** [comment]
Same Situation came to me When I started debug mode. 

This is not a right way, but can offer some trick for you.

```
inline fun <reified A : Activity> startActivity(): ActivityScenario<A> {
    val field = ActivityScenario::class.java.getDeclaredField("TIMEOUT_MILLISECONDS")
    field.isAccessible = true
    field.setLong(ActivityScenario::class, 10000000L)

    return ActivityScenario.launch(A::class.java)
}
```

**Comment by nihk** [comment]
@myungjunChae I'm not sure what that will achieve. My repository example times out after 45 seconds (the default value of `ActivityScenario.TIMEOUT_MILLISECONDS`. This would in theory make it instead time out after 10000 seconds?

**Comment by coreform** [comment]
Sigh, I was able to yield this issue after moving the instrumentation test from a library module (where there were other problems) to the app module. In my case the Activity exists within the presentation module but is referenced in the app module's AndroidManifest.xml. But also a TestActivity within the test (within app module) fails in this way too.
