### ISSUE TITLE
IOException in BasicScreenCaptureProcessor.process 

### ISSUE THREAD

**Issue by yogurtearl** [android/android-test#818]
### Description

`BasicScreenCaptureProcessor` uses a deprecated method (`Environment#getExternalStoragePublicDirectory`) for storing screenshot files. 

I know that `BasicScreenCaptureProcessor` might be deprecated someday... (https://github.com/android/android-test/issues/383), but would be nice if it worked in the mean time.

https://github.com/android/android-test/blob/7a8e7b79db529f530aa340b05bddad2b688a50f0/runner/android_junit_runner/java/androidx/test/runner/screenshot/BasicScreenCaptureProcessor.java#L52-L54

Could be replaced with this, which works on API 30 and back to at least API 23, likely further.
```java
  public BasicScreenCaptureProcessor() {
    this(new File(InstrumentationRegistry.getInstrumentation().getTargetContext().getFilesDir(), "screenshots"));
  }
```

### Steps to Reproduce

run `Screenshot.capture().process()` in a test on API 23 virtual device on FTL

### Expected Results

Saves screenshot to disk.

### Actual Results

Exception.
```
E/TestRunner(6545): Caused by: java.io.IOException: The directory /storage/emulated/0/Pictures/screenshots does not exist and could not be created or is not writable.
E/TestRunner(6545): 	at androidx.test.runner.screenshot.BasicScreenCaptureProcessor.process(BasicScreenCaptureProcessor.java:72)
E/TestRunner(6545): 	at androidx.test.runner.screenshot.ScreenCapture.process(ScreenCapture.java:140)
E/TestRunner(6545): 	at androidx.test.runner.screenshot.ScreenCapture.process(ScreenCapture.java:126)
E/TestRunner(6545): 	... 34 more
```

### AndroidX Test and Android OS Versions

AndroidX test 1.3.0, API 23

**Comment by sushantchoudhary** [comment]
Any update on this issue? or any other workaround to run tests on FTL with API 30?
