### ISSUE TITLE
adb shell am instrument -w -e testFile returns INSTRUMENTATION_RESULT: shortMsg=Process crashed.

### ISSUE THREAD

**Issue by bkmalkoc** [android/android-test#894]
### Description
Specific tests defined in testFile.txt is not running with testFile in shell command
### Steps to Reproduce
Created a testFile.txt that includes below

> com.package.name.instrumentation.Test1#test1
> com.package.name.instrumentation.Test2#test2
> com.package.name.instrumentation.Test3#test3

Run to push the file to device:
adb push testFile.txt /sdcard

Run the commands to push the apk and test apk to device:
./gradlew assembleDebug
./gradlew assembleDebugAndroidTest
./gradlew installDebug
./gradlew installDebugAndroidTest

 adb shell am instrument -w -e testFile /sdcard/testFile.txt com.package.name/android.support.test.runner.AndroidJUnitRunner

### Expected Results
To be run only test1, test2, test3 tests in emulator

### Actual Results
adb shell am instrument -w -e testFile /sdcard/testFile.txt com.package.name/android.support.test.runner.AndroidJUnitRunner
As a result of command:

INSTRUMENTATION_RESULT: shortMsg=Process crashed.
INSTRUMENTATION_CODE: 0

### AndroidX Test and Android OS Versions
androidx.test:core:1.2.0
androidx.test.espresso:espresso-core:3.2.0

Android OS - API 30

**Comment by adazh** [comment]
Thanks for reporting the issue! Do you mind also posting your logcat logs? The logcat logs should contain a stack trace that explains the reason why your app process crashed.

**Comment by bkmalkoc** [comment]
adb shell am instrument -w -e -D testFile /sdcard/testFile.txt com.package.name/android.support.test.runner.AndroidJUnitRunner
I run the script with "-D" argument to get a better log otherwise it looks like above.
The log:
```
android.util.AndroidException: INSTRUMENTATION_FAILED: /sdcard/testFile.txt
        at com.android.commands.am.Instrument.run(Instrument.java:519)
        at com.android.commands.am.Am.runInstrument(Am.java:202)
        at com.android.commands.am.Am.onRun(Am.java:80)
        at com.android.internal.os.BaseCommand.run(BaseCommand.java:60)
        at com.android.commands.am.Am.main(Am.java:50)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:399)
INSTRUMENTATION_STATUS: Error=Unable to find instrumentation info for: ComponentInfo{/sdcard/testFile.txt}
INSTRUMENTATION_STATUS: id=ActivityManagerService
INSTRUMENTATION_STATUS_CODE: -1

```

**Comment by adazh** [comment]
Thanks! Could you help me try on a lower API level? e.g. API 28 or 25.

**Comment by bkmalkoc** [comment]
Tested in API 25, 28 and 29 and same log returns.

**Comment by adazh** [comment]
Sorry, I missed that. The '-D' arg is misplaced here.

Can you re-run your test with your original adb command `adb shell am instrument -w -e testFile /sdcard/testFile.txt com.package.name/android.support.test.runner.AndroidJUnitRunner` on these API levels?

The logcat logs will give you more debugging information. To get the Logcat logs, you'll need to use the `adb logcat` command while running your tests. See https://developer.android.com/studio/command-line/logcat for usage.

**Comment by bkmalkoc** [comment]
run the command
adb shell am instrument -w -e testFile /sdcard/testFile.txt com.package.name.test/androidx.test.runner.AndroidJUnitRunner

logcat for api 28:
```
FATAL EXCEPTION: main
    Process: com.package.name, PID: 7278
    java.lang.RuntimeException: Exception thrown in onCreate() of ComponentInfo{com.package.name/androidx.test.runner.AndroidJUnitRunner}: java.lang.IllegalArgumentException: testfile not found: /sdcard/testFile.txt
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5868)
        at android.app.ActivityThread.access$1100(ActivityThread.java:199)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.IllegalArgumentException: testfile not found: /sdcard/testFile.txt
        at androidx.test.internal.runner.RunnerArgs$Builder.parseFromFile(RunnerArgs.java:454)
        at androidx.test.internal.runner.RunnerArgs$Builder.fromBundle(RunnerArgs.java:240)
        at androidx.test.runner.AndroidJUnitRunner.parseRunnerArgs(AndroidJUnitRunner.java:339)
        at androidx.test.runner.AndroidJUnitRunner.onCreate(AndroidJUnitRunner.java:279)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5863)
        at android.app.ActivityThread.access$1100(ActivityThread.java:199) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
     Caused by: java.io.FileNotFoundException: /sdcard/testFile.txt (Permission denied)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:231)
        at java.io.FileInputStream.<init>(FileInputStream.java:165)
        at java.io.FileReader.<init>(FileReader.java:72)
        at androidx.test.internal.runner.RunnerArgs$Builder.openFile(RunnerArgs.java:480)
        at androidx.test.internal.runner.RunnerArgs$Builder.parseFromFile(RunnerArgs.java:443)
```

logcat for API 30:
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.package.name, PID: 8097
    java.lang.RuntimeException: Exception thrown in onCreate() of ComponentInfo{com.package.name/androidx.test.runner.AndroidJUnitRunner}: java.lang.IllegalArgumentException: testfile not found: /sdcard/testFile.txt
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6709)
        at android.app.ActivityThread.access$1300(ActivityThread.java:237)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.IllegalArgumentException: testfile not found: /sdcard/testFile.txt
        at androidx.test.internal.runner.RunnerArgs$Builder.parseFromFile(RunnerArgs.java:454)
        at androidx.test.internal.runner.RunnerArgs$Builder.fromBundle(RunnerArgs.java:240)
        at androidx.test.runner.AndroidJUnitRunner.parseRunnerArgs(AndroidJUnitRunner.java:339)
        at androidx.test.runner.AndroidJUnitRunner.onCreate(AndroidJUnitRunner.java:279)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6704)
        at android.app.ActivityThread.access$1300(ActivityThread.java:237) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
     Caused by: java.io.FileNotFoundException: /sdcard/testFile.txt: open failed: ENOENT (No such file or directory)
        at libcore.io.IoBridge.open(IoBridge.java:492)
        at java.io.FileInputStream.<init>(FileInputStream.java:160)
        at java.io.FileReader.<init>(FileReader.java:72)
        at androidx.test.internal.runner.RunnerArgs$Builder.openFile(RunnerArgs.java:480)
        at androidx.test.internal.runner.RunnerArgs$Builder.parseFromFile(RunnerArgs.java:443)
        at androidx.test.internal.runner.RunnerArgs$Builder.fromBundle(RunnerArgs.java:240) 
        at androidx.test.runner.AndroidJUnitRunner.parseRunnerArgs(AndroidJUnitRunner.java:339) 
        at androidx.test.runner.AndroidJUnitRunner.onCreate(AndroidJUnitRunner.java:279) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6704) 
        at android.app.ActivityThread.access$1300(ActivityThread.java:237) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
     Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
        at libcore.io.Linux.open(Native Method)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:254)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
        at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7542)

**Comment by adazh** [comment]
Thanks. So it looks like it's a permission issue: `AndroidJUnitRunner` was not able to read the `testFile.txt`.

You could try to put the `testFile.text` under `/data/local/tmp` or the `/data/data/${your.package}` folder, where `AndroidJUnitRunner` has the permission to access.

**Comment by bkmalkoc** [comment]
Putting the file under `/data/local/tmp` and running the script with it made it work. You may wanna edit the [documentation](https://developer.android.com/reference/androidx/test/runner/AndroidJUnitRunner) as well with this permission information. Thanks.

**Comment by adazh** [comment]
Right, the documentation needs to be updated. Great to know it work. Closing this issue.
